### ISSUE TITLE
question. SAP diagnostic agent publishing data to cloud watch

### ISSUE THREAD

**Issue by MykhailoPrykhodko** [aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver#10]
Hi team
Is anybody thought or possibly tried to publish the data from OS level - sap diagnostic agent - to AWS Cloud watch?
The background of this topic is monitoring the certificate expiration. A possible similar idea already has been discussed as part of an actual solution.

**Comment by frumania** [comment]
Not that i am aware of. As the SAP Diagnostic Agent is tailored to SAP Solman, does tit have an "API / interface", that we could hook up to?
