### ISSUE TITLE
eu-south-1 region - not supported. manual Procedure - do not work

### ISSUE THREAD

**Issue by picoroma** [aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver#11]
I'm trying to use the manual procedure for deploy the lamda function with a cf template.
Unfortunately what described here - form manual steps:
https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver/blob/master/docs/Deploy_Manually.md
DO NOT WORK
I created manually the S3 bucket.
I upload into the bucket the "packaged.yml" file
After that I run the deploy with CF template - using the URL to the packaged.yml file.
The deploy finish with error :

CWLambdaFunction	
CREATE_FAILED	Resource handler returned message: "Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: **The specified key does not exist**. (Service: Lambda, Status Code: 400, Request ID: 05710ed5-6889-4e4f-b4cb-445590767b39)" (RequestToken: 69bdc014-1995-515b-9ed2-1aca9b9c676e, HandlerErrorCode: InvalidRequest)

Seems to looking for a S3 Key?
How can I create the key and put into the bucket ?
NOTE: I opened a CASE for this even at AWS support. 
THX
P.

**Comment by picoroma** [comment]
Other Issue.
When run the DEPLOY.SH bash file from a EC2 instance in MILAN.
THis step:
# Copy Artifacts
echo "Copy artifacts to S3 Bucket"
aws s3 cp s3://sap-monitor/$releaseID s3://$accountid-sapmonitor --source-region eu-central-1
finish with error:

download failed: s3://sap-monitor/c84d6466a4a9a312c9d83b97a21bb366 to ./c84d6466a4a9a312c9d83b97a21bb366 An error occurred (IllegalLocationConstraintException) when calling the GetObject operation: The eu-central-1 location constraint is incompatible for the region specific endpoint this request was sent to.

**Comment by frumania** [comment]
Thanks for reporting, let me investigate and come back.

**Comment by picoroma** [comment]
In the meantime I have found a workaround.I downloaded all the file requested into the yml file.Put these files into my s3 bucket where is also the yml file.Deploy the CF template works fine in this way...P.Il 17 mag 2022 16:40, Marcel Törpe ***@***.***> ha scritto:
Thanks for reporting, let me investigate and come back.

**Comment by frumania** [comment]
Just verified the script again.

Works fine in Cloud9 and CloudShell.
Random EC2 instance won't work, unless you provide proper authorizations (e.g. STS).
