### ISSUE TITLE
GRAFANA Dashboard

### ISSUE THREAD

**Issue by picoroma** [aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver#12]
Hi! 
Is there a way to export\migrate the CW Dashboard into a GRAFANA compatible one?
Can you provide also a GRAFANA sample dashboard, please ?
THX

**Comment by frumania** [comment]
You should simply be able to use the Grafana-CloudWatch integration:
https://grafana.com/docs/grafana/next/datasources/aws-cloudwatch/

Then simply re-model the dasboard to your desire!

**Comment by picoroma** [comment]
Yes. I'm using it.
And I can catch all the metrics.
But GRAFANA use a different query languages...

**Comment by frumania** [comment]
I see, but for most metrics there is no formula or anything. Simply display the figure/number should do it?!
