### ISSUE TITLE
S3 access error with deploying this application

### ISSUE THREAD

**Issue by Rajdeepkoch** [aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver#2]
While trying to deploy this application in us-west-2 where our application runs we are getting the below S3 access error. Can you please suggest what could be the reason for this & what can be done to solve it. the eu-central-1 region is locked for our account for any activities so i am not sure why its going there & how do we overcome this.

Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: eu-central-1. Please use this region to retry the request (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 2783e3d6-9f17-4167-b770-bd2e4b0b1fd7; Proxy: null)

Screenshot also attached for the same

![image](https://user-images.githubusercontent.com/77342170/104956573-6b2cfc00-59f2-11eb-96eb-57cbe18aa736.png)
<img width="569" alt="Deployment error" src="https://user-images.githubusercontent.com/77342170/104956587-72540a00-59f2-11eb-84d3-b897a4aa2cad.png">

**Comment by frumania** [comment]
Hi,

added CF templates for us-east-1 & us-west-2:

[North Virginia (us-east-1)](https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver/blob/master/packaged-us-east-1.yml)
[Oregon (us-west-2)](https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver/blob/master/packaged-us-west-2.yml)
