### ISSUE TITLE
We are facing issue while Testing the Lambda function after the deployment of sap-monior.

### ISSUE THREAD

**Issue by Melvin-Koch** [aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver#3]
2021-01-21T01:05:02.444+05:30	START RequestId: #################################### Version: $LATEST

2021-01-21T01:05:02.466+05:30	Reset config!

2021-01-21T01:05:02.551+05:30	Downloading config from AWS Secrets Manager: sap-monitor-CR1

2021-01-21T01:05:13.267+05:30	Found destination CR1

2021-01-21T01:05:13.907+05:30	JCo initialization failed with java.lang.UnsatisfiedLinkError: no sapjco3 in java.library.path: [/var/lang/lib, /lib64, /usr/lib64, /var/runtime, /var/runtime

JCo initialization failed with java.lang.UnsatisfiedLinkError: no sapjco3 in java.library.path: [/var/lang/lib, /lib64, /usr/lib64, /var/runtime, /var/runtime/lib, /var/task, /var/task/lib, /opt/lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]: java.lang.ExceptionInInitializerErrorjava.lang.ExceptionInInitializerError: JCo initialization failed with java.lang.UnsatisfiedLinkError: no sapjco3 in java.library.path: [/var/lang/lib, /lib64, /usr/lib64, /var/runtime, /var/runtime/lib, /var/task, /var/task/lib, /opt/lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]	at com.sap.conn.jco.rt.MiddlewareJavaRfc.<clinit>(MiddlewareJavaRfc.java:165)	at com.sap.conn.jco.rt.DefaultJCoRuntime.initialize(DefaultJCoRuntime.java:78)	at com.sap.conn.jco.rt.JCoRuntimeFactory.<clinit>(JCoRuntimeFactory.java:23)	at com.sap.conn.jco.rt.RuntimeEnvironment.<init>(RuntimeEnvironment.java:40)	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)	at java.base/java.lang.Class.newInstance(Unknown Source)	at com.sap.conn.jco.ext.Environment.getInstance(Environment.java:164)	at com.sap.conn.jco.ext.Environment.isDestinationDataProviderRegistered(Environment.java:499)	at Config.readSecretsFromSecretManager(Config.java:174)	at Config.readSecrets(Config.java:122)	at init.handleRequest(init.java:61)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

2021-01-21T01:05:13.908+05:30	END RequestId: 11######################

2021-01-21T01:05:13.908+05:30	REPORT RequestId: ###################### Duration: 11463.02 ms Billed Duration: 11464 ms Memory Size: 512 MB Max Memory Used: 163 MB Init Durati

After checking the few of the related blogs we found that, we need to have .jar file at the OS level.
Could you please advice on the same.

**Comment by frumania** [comment]
I have found a glitch with the JAVA deployment package.

Kindly retry = redeploy with the given CF templates:

[North Virginia (us-east-1)](https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver/blob/master/packaged-us-east-1.yml)
[Oregon (us-west-2)](https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver/blob/master/packaged-us-west-2.yml)
