### ISSUE TITLE
Connection to the message server instead of dialog instance

### ISSUE THREAD

**Issue by MykhailoPrykhodko** [aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver#4]
Hi 
Could you please check if it is possible to add the message server connection, instead of the direct connection to the dialog instance?
The reason for that to have statistics independently if one of the dialog instances will be unavailable, for example from the maintenance or other perspectives.

**Comment by frumania** [comment]
Good point, that should not be too hard to add.
I will come back to you!

**Comment by frumania** [comment]
Alright, here you go:

https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver/blob/master/docs/Message_Server.md
