### ISSUE TITLE
New ideas

### ISSUE THREAD

**Issue by MykhailoPrykhodko** [aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver#5]
Hi Marcel,
I'd like your ideas for the functionality extension.
Do you plan to build a new version this year?

**Comment by frumania** [comment]
Hi Mykhailo,
thanks for asking.
I am open to that, is there any specific feature you'd love to see?

**Comment by MykhailoPrykhodko** [comment]
I would say your list is pretty good, plus I have added some ideas to the end
- Number of Dumps (st22) - will be very useful 
- Number of critical syslog issues (sm21) - will be very useful 
- Number of failed/pending IDOCs (we02) - will be good to see including IDOC types and statuses.
- Number of aborted/failed jobs (se37) - will be very useful 
- Odata Statistics
- Business Metrics e.g. Open Sales Orders - this is an interesting idea, possible can be realized as part of the available functionality "https://launchpad.support.sap.com/#/financialdataquality/". But in general very individual and better to have as a separate product/deployment without mix up with general technical monitoring.
- st03 other tasktypes

Idea from my end
- NSE (Native Storage Extention) monitoring - can be realized via ABAP or HANA. If interesting I can add technical details, kind of SQL, program, notes. Topic relevant only for systems on HANA (S4/ERP/BW/BW4).
- monitoring of the archive link  - for example, archiving queue for print list. https://itsiti.com/oam1-archivelink-monitor/

**Comment by frumania** [comment]
I managed to add
- Number of Dumps (st22)
- Number of critical syslog issues (sm21)
- Number of failed/pending IDOCs (we02)

Kindly check it out ;) -> v.1.06
I might add further metrics based on customer feedback.
