### ISSUE TITLE
deploy script issue

### ISSUE THREAD

**Issue by MykhailoPrykhodko** [aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver#7]
Hi when I'm using the manual deployment option https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver/blob/master/docs/Deploy_Manually.md

I'm receiving the error on a step 
# Copy Artifacts
echo "Copy artifacts to S3 Bucket"
aws s3 cp s3://sap-monitor/$releaseID s3://$accountid-sapmonitor --source-region eu-central-1
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by frumania** [comment]
Did you run it from AWS CloudShell?

Cause the strings "$releaseID" & "$accountid" should actually have been substituted.

**Comment by MykhailoPrykhodko** [comment]
Solved. It was my mistake, sorry for the disturbance
