### ISSUE TITLE
app not visible via AWS Serverless Application Repository

### ISSUE THREAD

**Issue by MykhailoPrykhodko** [aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver#8]
Hi for some reason app is not visible via AWS Serverless Application Repository - region Frankfurt 
https://eu-central-1.console.aws.amazon.com/serverlessrepo/home?region=eu-central-1#/available-applications

**Comment by frumania** [comment]
It is visible for me, you just have to tick the box "Show apps that create custom IAM roles or resource policies"

![test](https://i.imgur.com/U6ZMeyC.png)
