### ISSUE TITLE
Strange behaviors

### ISSUE THREAD

**Issue by MykhailoPrykhodko** [aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver#9]
Hi @frumania 
This is not an issue, just sharing some use cases, possible will help to improve the solution.
We had a situation with high memory usage on abap side, as a result, the SMON started showing the Free memory metrics = 0.
But ST06 at the same time shows correct statistics.
We have fixed the issue with high memory usage, but SMON still not showing the data. We are checking the root cause.

**Comment by frumania** [comment]
Good to know! Maybe worth opening a ticket with SAP?

**Comment by frumania** [comment]
Did you find out the root cause by chance?

**Comment by MykhailoPrykhodko** [comment]
Was my mistake because of the company restrictions on the AWS policies.
